### ISSUE TITLE
Documentation Editorial Cleanup -- Design System 

### ISSUE THREAD

**Issue by oanelson** [nmfs-ocio/radfish#140]
Edit the Design System pages for voice, tone, and clarity. Add descriptions, diagrams, links, etc. as needed.

- https://nmfs-radfish.github.io/radfish/design-system/custom-components
- https://nmfs-radfish.github.io/radfish/design-system/custom-components/application-container
- https://nmfs-radfish.github.io/radfish/design-system/custom-components/date-picker
- https://nmfs-radfish.github.io/radfish/design-system/custom-components/table
- https://nmfs-radfish.github.io/radfish/design-system/us-web-design-system

- [x] #155 - @jaygiang

**Comment by theangchen** [comment]
@oanelson -  @jaygiang Will be reaching out to you to help add the description to the card pages if you can just provide him the copy.

**Comment by theangchen** [comment]
@jaygiang to help with setup and configs:
Option 1: https://docusaurus.io/docs/sidebar/items#category-link
Option 2: https://github.com/facebook/docusaurus/blob/5a883b4008f3258c1cf585ad01d419d038e4de78/website/docs/advanced/index.mdx
https://docusaurus.io/docs/advanced

**Comment by jaygiang** [comment]
Hi @oanelson , would you like to be able to add text above the cards and/or below the cards like so - https://docusaurus.io/docs/advanced

![Image](https://github.com/user-attachments/assets/99145270-8f8d-425d-9cd9-956d07c49041)

**Comment by oanelson** [comment]
Yes, that's exactly what I'm trying to do!

**Comment by jaygiang** [comment]
@oanelson sounds great! I made a [subtask](https://github.com/NMFS-RADFish/radfish/issues/155) and created this [pull request](https://github.com/NMFS-RADFish/radfish/pull/156) to allow you to add text above and below the category cards.

After the team reviews and merges it, I'll update you on how to use it. 

cc: @theangchen

**Comment by jaygiang** [comment]
@oanelson The `main` branch is now updated with the latest changes, so feel free to pull that down to your local environment. The `category.json` files have been changed to `index.mdx` files which allows you to add text above and/or below the cards. 

For example docs > developer-documentation > building-your-application. You can add your text as stated in the comments:

```mdx
# Building Your Application

{/* Write top text here */}


import DocCardList from '@theme/DocCardList';

<DocCardList />


{/* Write bottom text here */}
```

If you have any questions, please let me know! I'm happy to go over this in a video chat too if you'd like.
