### ISSUE TITLE
Docs - Update Patterns > Offline Storage documentation

### ISSUE THREAD

**Issue by brockinit** [nmfs-ocio/radfish#49]
This shouldn't be empty. Use the documentation within the [boilerplate README](https://github.com/NMFS-RADFish/boilerplate?tab=readme-ov-file#offline-storage) to fill in this section. 

Ideally, we just remove the boilerplate README section as well since we're using that less nowadays.

**Comment by theangchen** [comment]
Changes requested in PR, moving back to in progress
